api:
  dashboard: true
  insecure: true  # For testing only, use secure in production

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: ":443"
    
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: home-net
  file:
    directory: "/etc/traefik/dynamic"
    watch: true

log:
  level: "DEBUG"